### ISSUE TITLE
POJ P3272题解的二分查找教程链接失效了

### ISSUE THREAD

**Issue by AegirVOD** [amoshyc/ojsolution#5]
望更正 期待您的题解
https://amoshyc.github.io/ojsolution-build/poj/p3273.html

**Comment by amoshyc** [comment]
This repo has been deprecated and moved to [here](https://github.com/amoshyc/CPsolution). 
The new github page is https://amoshyc.github.io/CPsolution/.
Issue fixed. Thank you.
